/*
    Generated by yapc -- An LR(1) parser generator made by CFY
*/



#include <stdio.h>
#include "grammar_builder.h"
#include "grammar.h"
#include "spool.h"

#include "yparser.h"
static const int yytokenCount = 24;
static const int yyntCount = 21;
#ifndef YYMALLOC
    #define YYMALLOC malloc
#endif
#ifndef YYREALLOC
    #define YYREALLOC realloc
#endif
#ifndef YYFREE
    #define YYFREE free
#endif
#ifndef YYDESTRUCTOR
    #define YYDESTRUCTOR(a)
#endif
#define YYPUSH_STATE(s) \
    if(yyparser->sLen >= yyparser->sSize){ \
        yyparser->sSize *= 2; \
        yyparser->state = (int *)YYREALLOC(yyparser->state,sizeof(int) * yyparser->sSize); \
    } \
    yyparser->state[yyparser->sLen++] = (s);

#define YYSTATE() (yyparser->state[yyparser->sLen - 1])
#define YYCHECK_PUSH_TOKEN() \
    if(yyparser->sp - yyparser->pstack >= yyparser->pSize){\
        size_t offset = yyparser->sp - yyparser->pstack;\
        yyparser->pSize *= 2;\
        yyparser->pstack = (YToken *)YYREALLOC(yyparser->pstack,sizeof(YToken) * yyparser->pSize);\
        yyparser->sp = yyparser->pstack + offset;\
    }
/*
    shift action table
    positive numbers indicate the states shift to,
    negative numbers indicate the rules reduce with.
    the state should be the number in the table minus one,since zero marks
    for error.
*/
static const int yyshift[] = {
    /* state 0 */
         0,   -15,   -15,   -15,     0,     0,   -15,   -15,   -15,   -15,   -15,
         0,   -15,   -15,     0,     0,     0,     0,     0,     0,     0,     0,
         0,    65,
    /* state 1 */
        -1,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 2 */
         0,    -4,    -4,    -4,     0,     0,    -4,    -4,    -4,    -4,    -4,
         0,    -4,    -4,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 3 */
         0,    38,    41,    43,     0,     0,    45,    49,    50,    55,    60,
         0,    47,     5,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 4 */
         0,     0,     0,     0,    34,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,    14,     0,     0,     0,
         0,     0,
    /* state 5 */
         0,     0,     0,     0,    34,     0,     0,     0,     0,     0,     0,
         0,     0,     7,     0,     0,     0,     0,    14,     0,     0,     0,
         0,     0,
    /* state 6 */
        -2,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 7 */
         0,     0,     0,     0,   -23,     0,     0,     0,     0,     0,     0,
         0,     0,   -23,     0,     0,     0,     0,   -23,     0,     0,     0,
         0,     0,
    /* state 8 */
         0,     0,     0,     0,   -24,     0,     0,     0,     0,     0,     0,
         0,     0,   -24,     0,     0,     0,     0,   -24,     0,     0,     0,
         0,     0,
    /* state 9 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,    11,     0,     0,     0,     0,     0,
         0,     0,
    /* state 10 */
         0,     0,     0,     0,   -25,     0,     0,     0,     0,     0,     0,
         0,     0,   -25,     0,     0,     0,     0,   -25,     0,     0,     0,
         0,     0,
    /* state 11 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,    13,     0,     0,     0,     0,     0,
         0,     0,
    /* state 12 */
         0,     0,     0,     0,   -26,     0,     0,     0,     0,     0,     0,
         0,     0,   -26,     0,     0,     0,     0,   -26,     0,     0,     0,
         0,     0,
    /* state 13 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,   -30,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 14 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,    16,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 15 */
         0,     0,     0,     0,     0,    33,     0,     0,     0,     0,     0,
         0,     0,     0,     0,   -37,   -37,     0,   -37,     0,   -37,     0,
       -37,     0,
    /* state 16 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,   -33,   -31,     0,     0,     0,     0,     0,
         0,     0,
    /* state 17 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,    19,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 18 */
         0,     0,     0,     0,     0,    33,     0,     0,     0,     0,     0,
         0,     0,     0,     0,   -37,   -37,     0,   -37,     0,   -37,     0,
       -37,     0,
    /* state 19 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,   -34,   -34,     0,    30,     0,    29,     0,
        31,     0,
    /* state 20 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
        23,     0,     0,     0,   -38,   -38,     0,   -38,     0,   -38,     0,
       -38,     0,
    /* state 21 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,   -35,   -35,     0,   -35,     0,   -35,     0,
       -35,     0,
    /* state 22 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,    24,     0,
         0,     0,
    /* state 23 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,   -39,   -39,    27,   -39,    26,   -39,     0,
       -39,     0,
    /* state 24 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,   -40,   -40,     0,   -40,     0,   -40,     0,
       -40,     0,
    /* state 25 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,   -41,   -41,     0,   -41,     0,   -41,     0,
       -41,     0,
    /* state 26 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,    28,     0,     0,
         0,     0,
    /* state 27 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,   -42,   -42,     0,   -42,     0,   -42,     0,
       -42,     0,
    /* state 28 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       -43,     0,     0,     0,   -43,   -43,     0,   -43,     0,   -43,     0,
       -43,     0,
    /* state 29 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       -44,     0,     0,     0,   -44,   -44,     0,   -44,     0,   -44,     0,
       -44,     0,
    /* state 30 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       -45,     0,     0,     0,   -45,   -45,     0,   -45,     0,   -45,     0,
       -45,     0,
    /* state 31 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,   -32,   -32,     0,    30,     0,    29,     0,
        31,     0,
    /* state 32 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,   -36,   -36,     0,   -36,     0,   -36,     0,
       -36,     0,
    /* state 33 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,   -29,     0,     0,     0,   -29,     0,
         0,     0,
    /* state 34 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,   -27,     0,     0,     0,    36,     0,
         0,     0,
    /* state 35 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,   -28,     0,     0,     0,   -28,     0,
         0,     0,
    /* state 36 */
         0,    -3,    -3,    -3,     0,     0,    -3,    -3,    -3,    -3,    -3,
         0,    -3,    -3,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 37 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,    39,     0,
         0,     0,
    /* state 38 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,    40,
         0,     0,
    /* state 39 */
         0,    -5,    -5,    -5,     0,     0,    -5,    -5,    -5,    -5,    -5,
         0,    -5,    -5,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 40 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,    42,
         0,     0,
    /* state 41 */
         0,    -6,    -6,    -6,     0,     0,    -6,    -6,    -6,    -6,    -6,
         0,    -6,    -6,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 42 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,    44,
         0,     0,
    /* state 43 */
         0,    -7,    -7,    -7,     0,     0,    -7,    -7,    -7,    -7,    -7,
         0,    -7,    -7,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 44 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,    46,
         0,     0,
    /* state 45 */
         0,    -8,    -8,    -8,     0,     0,    -8,    -8,    -8,    -8,    -8,
         0,    -8,    -8,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 46 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,    48,
         0,     0,
    /* state 47 */
         0,    -9,    -9,    -9,     0,     0,    -9,    -9,    -9,    -9,    -9,
         0,    -9,    -9,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 48 */
         0,   -10,   -10,   -10,     0,     0,   -10,   -10,   -10,   -10,   -10,
         0,   -10,   -10,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 49 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,   -16,     0,
         0,     0,
    /* state 50 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,    54,     0,
         0,     0,
    /* state 51 */
         0,   -11,   -11,   -11,     0,     0,   -11,   -11,   -11,   -11,   -11,
         0,   -11,   -11,     0,     0,     0,     0,     0,     0,    53,     0,
         0,     0,
    /* state 52 */
         0,   -17,   -17,   -17,     0,     0,   -17,   -17,   -17,   -17,   -17,
         0,   -17,   -17,     0,     0,     0,     0,     0,     0,   -17,     0,
         0,     0,
    /* state 53 */
         0,   -18,   -18,   -18,     0,     0,   -18,   -18,   -18,   -18,   -18,
         0,   -18,   -18,     0,     0,     0,     0,     0,     0,   -18,     0,
         0,     0,
    /* state 54 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,   -16,     0,
         0,     0,
    /* state 55 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,    59,     0,
         0,     0,
    /* state 56 */
         0,   -12,   -12,   -12,     0,     0,   -12,   -12,   -12,   -12,   -12,
         0,   -12,   -12,     0,     0,     0,     0,     0,     0,    58,     0,
         0,     0,
    /* state 57 */
         0,   -19,   -19,   -19,     0,     0,   -19,   -19,   -19,   -19,   -19,
         0,   -19,   -19,     0,     0,     0,     0,     0,     0,   -19,     0,
         0,     0,
    /* state 58 */
         0,   -20,   -20,   -20,     0,     0,   -20,   -20,   -20,   -20,   -20,
         0,   -20,   -20,     0,     0,     0,     0,     0,     0,   -20,     0,
         0,     0,
    /* state 59 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,   -16,     0,
         0,     0,
    /* state 60 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,    64,     0,
         0,     0,
    /* state 61 */
         0,   -13,   -13,   -13,     0,     0,   -13,   -13,   -13,   -13,   -13,
         0,   -13,   -13,     0,     0,     0,     0,     0,     0,    63,     0,
         0,     0,
    /* state 62 */
         0,   -21,   -21,   -21,     0,     0,   -21,   -21,   -21,   -21,   -21,
         0,   -21,   -21,     0,     0,     0,     0,     0,     0,   -21,     0,
         0,     0,
    /* state 63 */
         0,   -22,   -22,   -22,     0,     0,   -22,   -22,   -22,   -22,   -22,
         0,   -22,   -22,     0,     0,     0,     0,     0,     0,   -22,     0,
         0,     0,
    /* state 64 */
         0,   -14,   -14,   -14,     0,     0,   -14,   -14,   -14,   -14,   -14,
         0,   -14,   -14,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
};
/*
    goto table
*/
static const int yygoto[] = {
    /* state 0 */
         0,     2,     0,     0,     3,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 1 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 2 */
         0,     0,     4,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 3 */
         0,     0,     0,    37,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 4 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     6,     9,
        12,     0,    10,     0,     0,     0,     0,     0,     0,     0,
    /* state 5 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     8,
        12,     0,    10,     0,     0,     0,     0,     0,     0,     0,
    /* state 6 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 7 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 8 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 9 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 10 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 11 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 12 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 13 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,    15,     0,     0,     0,     0,     0,     0,
    /* state 14 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 15 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,    17,     0,    32,     0,     0,     0,
    /* state 16 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,    18,     0,     0,     0,     0,
    /* state 17 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 18 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,    20,     0,     0,     0,
    /* state 19 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,    21,
    /* state 20 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,    22,     0,     0,
    /* state 21 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 22 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 23 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,    25,     0,
    /* state 24 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 25 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 26 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 27 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 28 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 29 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 30 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 31 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,    21,
    /* state 32 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 33 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,    35,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 34 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 35 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 36 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 37 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 38 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 39 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 40 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 41 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 42 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 43 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 44 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 45 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 46 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 47 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 48 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 49 */
         0,     0,     0,     0,     0,    51,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 50 */
         0,     0,     0,     0,     0,     0,    52,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 51 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 52 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 53 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 54 */
         0,     0,     0,     0,     0,    56,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 55 */
         0,     0,     0,     0,     0,     0,     0,    57,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 56 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 57 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 58 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 59 */
         0,     0,     0,     0,     0,    61,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 60 */
         0,     0,     0,     0,     0,     0,     0,     0,    62,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 61 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 62 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 63 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 64 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
};
/*
    the left hand side of each rule,used to determine goto action.
*/
static const int yylhs[] = {
         0,     1,     2,     2,     3,     3,     3,     3,     3,     3,     3,
         3,     3,     4,     4,     5,     6,     6,     7,     7,     8,     8,
         9,     9,    10,    10,    11,    12,    12,    14,    13,    15,    16,
        15,    17,    17,    17,    18,    18,    18,    19,    19,    20,    20,
        20,
};
/*
    the length of the symbols on the rhs of each rule
    used to pop states from the state stack when doing
    an reduction.
*/
static const int yyruleLen[] = {
         1,     5,     2,     0,     3,     2,     2,     2,     2,     1,     3,
         3,     3,     1,     0,     0,     2,     1,     2,     1,     2,     1,
         2,     1,     2,     2,     2,     2,     0,     0,     4,     1,     0,
         4,     3,     1,     0,     0,     2,     3,     1,     2,     1,     1,
         1,
};
const char *yytokenNames[] = {
    "EOF","%token","%type","%datatype","%test","%empty",
    "%token_prefix","%enable_cst","%left","%right","%nonassoc","%prec",
    "%namespace","%%",":","|",";","-",
    "name","NUM","token","string","block","prologue",
    
};
const char *yytokenAlias[] = {
    "EOF","TOKEN_DIR","TYPE_DIR","DATATYPE_DIR","TEST_DIR","EMPTY_DIR",
    "TOKEN_PREFIX_DIR","ENABLE_CST_DIR","LEFT_DIR","RIGHT_DIR","NONASSOC_DIR","PREC_DIR",
    "NS_DIR","SEPERATOR","ARROW","OR","EOL","NEG",
    "NAME","NUM","TOKEN","STRING","BLOCK","PROLOGUE",
    
};
const char *yynonTerminals[] = {
    "(accept)","file","options","option","prologue","incPr",
    "leftTokens","rightTokens","nonassocTokens","body","bodyItem","test",
    "tokenList","rule","@1","ruleBody","@2","ruleItems",
    "rulePrec","num","ruleItem",
};
static int yyParser_reduce(yyParser *yyparser,int yyrule){
    YYCHECK_PUSH_TOKEN();
    YToken yyval;
    YGBuilder *yydata = (YGBuilder *)yyparser->userData;
    switch(yyrule){
        case 0:
            /* (accept) -> file  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 1:
            /* file -> prologue options <%%> body <%%>  */
            /* no action. */
            yyval = yyparser->sp[-5];
            yyparser->sp -= 5;
            *yyparser->sp++ = yyval;
            break;
        case 2:
            /* options -> options option  */
            /* no action. */
            yyval = yyparser->sp[-2];
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 3:
            /* options ->  */
            /* no action. */
            yyval = yyparser->sp[0];
            *yyparser->sp++ = yyval;
            break;
        case 4:
            /* option -> <%token> <token> <string>  */
            #line 79 "yparser.y"
            { YGBuilder_addToken(yydata,&(yyparser->sp[-2]),&(yyparser->sp[-1])); }
            #line 590 "yparser.c"
            yyparser->sp -= 3;
            *yyparser->sp++ = yyval;
            break;
        case 5:
            /* option -> <%type> <string>  */
            #line 80 "yparser.y"
            { yydata->stype = (yyparser->sp[-1]).image; }
            #line 598 "yparser.c"
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 6:
            /* option -> <%datatype> <string>  */
            #line 81 "yparser.y"
            { yydata->dataType = (yyparser->sp[-1]).image; }
            #line 606 "yparser.c"
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 7:
            /* option -> <%token_prefix> <string>  */
            #line 82 "yparser.y"
            { yydata->tokenPrefix = (yyparser->sp[-1]).image; }
            #line 614 "yparser.c"
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 8:
            /* option -> <%namespace> <string>  */
            #line 83 "yparser.y"
            { yydata->nameSpace = (yyparser->sp[-1]).image; }
            #line 622 "yparser.c"
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 9:
            /* option -> <%enable_cst>  */
            #line 84 "yparser.y"
            { yydata->genCst = 1; }
            #line 630 "yparser.c"
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 10:
            /* option -> <%left> incPr leftTokens  */
            /* no action. */
            yyval = yyparser->sp[-3];
            yyparser->sp -= 3;
            *yyparser->sp++ = yyval;
            break;
        case 11:
            /* option -> <%right> incPr rightTokens  */
            /* no action. */
            yyval = yyparser->sp[-3];
            yyparser->sp -= 3;
            *yyparser->sp++ = yyval;
            break;
        case 12:
            /* option -> <%nonassoc> incPr nonassocTokens  */
            /* no action. */
            yyval = yyparser->sp[-3];
            yyparser->sp -= 3;
            *yyparser->sp++ = yyval;
            break;
        case 13:
            /* prologue -> <prologue>  */
            #line 89 "yparser.y"
            { yydata->prologue = (yyparser->sp[-1]).image; }
            #line 659 "yparser.c"
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 14:
            /* prologue ->  */
            /* no action. */
            yyval = yyparser->sp[0];
            *yyparser->sp++ = yyval;
            break;
        case 15:
            /* incPr ->  */
            #line 91 "yparser.y"
            { yydata->prLevel++; }
            #line 673 "yparser.c"
            *yyparser->sp++ = yyval;
            break;
        case 16:
            /* leftTokens -> leftTokens <token>  */
            #line 94 "yparser.y"
            { YGBuilder_setTokenPrecedence(yydata,&(yyparser->sp[-1]),YP_LEFT); }
            #line 680 "yparser.c"
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 17:
            /* leftTokens -> <token>  */
            #line 95 "yparser.y"
            { YGBuilder_setTokenPrecedence(yydata,&(yyparser->sp[-1]),YP_LEFT); }
            #line 688 "yparser.c"
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 18:
            /* rightTokens -> rightTokens <token>  */
            #line 97 "yparser.y"
            { YGBuilder_setTokenPrecedence(yydata,&(yyparser->sp[-1]),YP_RIGHT); }
            #line 696 "yparser.c"
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 19:
            /* rightTokens -> <token>  */
            #line 98 "yparser.y"
            { YGBuilder_setTokenPrecedence(yydata,&(yyparser->sp[-1]),YP_RIGHT); }
            #line 704 "yparser.c"
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 20:
            /* nonassocTokens -> nonassocTokens <token>  */
            #line 100 "yparser.y"
            { YGBuilder_setTokenPrecedence(yydata,&(yyparser->sp[-1]),YP_NONASSOC); }
            #line 712 "yparser.c"
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 21:
            /* nonassocTokens -> <token>  */
            #line 101 "yparser.y"
            { YGBuilder_setTokenPrecedence(yydata,&(yyparser->sp[-1]),YP_NONASSOC); }
            #line 720 "yparser.c"
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 22:
            /* body -> body bodyItem  */
            /* no action. */
            yyval = yyparser->sp[-2];
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 23:
            /* body -> bodyItem  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 24:
            /* bodyItem -> rule <;>  */
            /* no action. */
            yyval = yyparser->sp[-2];
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 25:
            /* bodyItem -> test <;>  */
            /* no action. */
            yyval = yyparser->sp[-2];
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 26:
            /* test -> <%test> tokenList  */
            #line 107 "yparser.y"
            { YGBuilder_commitTest(yydata); }
            #line 756 "yparser.c"
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 27:
            /* tokenList -> tokenList <token>  */
            #line 109 "yparser.y"
            { YGBuilder_addTestToken(yydata,&(yyparser->sp[-1])); }
            #line 764 "yparser.c"
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 28:
            /* tokenList ->  */
            /* no action. */
            yyval = yyparser->sp[0];
            *yyparser->sp++ = yyval;
            break;
        case 29:
            /* @1 ->  */
            #line 112 "yparser.y"
            { yydata->lhs = (yyparser->sp[-1]).image;YGBuilder_prepareRule(yydata,yydata->lhs); }
            #line 778 "yparser.c"
            break;
        case 30:
            /* rule -> <name> @1 <:> ruleBody  */
            /* no action. */
            yyval = yyparser->sp[-3];
            yyparser->sp -= 3;
            *yyparser->sp++ = yyval;
            break;
        case 31:
            /* ruleBody -> ruleItems  */
            #line 115 "yparser.y"
            { YGBuilder_commitRule(yydata); }
            #line 791 "yparser.c"
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 32:
            /* @2 ->  */
            #line 116 "yparser.y"
            { YGBuilder_prepareRule(yydata,yydata->lhs); }
            #line 799 "yparser.c"
            break;
        case 33:
            /* ruleBody -> ruleBody @2 <|> ruleItems  */
            #line 116 "yparser.y"
            { YGBuilder_commitRule(yydata); }
            #line 805 "yparser.c"
            yyparser->sp -= 3;
            *yyparser->sp++ = yyval;
            break;
        case 34:
            /* ruleItems -> ruleItems ruleItem rulePrec  */
            /* no action. */
            yyval = yyparser->sp[-3];
            yyparser->sp -= 3;
            *yyparser->sp++ = yyval;
            break;
        case 35:
            /* ruleItems -> <%empty>  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 36:
            /* ruleItems ->  */
            /* no action. */
            yyval = yyparser->sp[0];
            *yyparser->sp++ = yyval;
            break;
        case 37:
            /* rulePrec ->  */
            /* no action. */
            yyval = yyparser->sp[0];
            *yyparser->sp++ = yyval;
            break;
        case 38:
            /* rulePrec -> <%prec> <token>  */
            #line 122 "yparser.y"
            { YGBuilder_setRulePrecedence(yydata,&(yyparser->sp[-1]),NULL); }
            #line 839 "yparser.c"
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 39:
            /* rulePrec -> <%prec> <token> num  */
            #line 123 "yparser.y"
            { YGBuilder_setRulePrecedence(yydata,&(yyparser->sp[-2]),&(yyparser->sp[-1])); }
            #line 847 "yparser.c"
            yyparser->sp -= 3;
            *yyparser->sp++ = yyval;
            break;
        case 40:
            /* num -> <NUM>  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 41:
            /* num -> <-> <NUM>  */
            #line 125 "yparser.y"
            { yyval.num = -(yyparser->sp[-1]).num; }
            #line 862 "yparser.c"
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 42:
            /* ruleItem -> <token>  */
            #line 128 "yparser.y"
            { YGBuilder_addRuleItem(yydata,(yyparser->sp[-1]).image,1); }
            #line 870 "yparser.c"
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 43:
            /* ruleItem -> <name>  */
            #line 129 "yparser.y"
            { YGBuilder_addRuleItem(yydata,(yyparser->sp[-1]).image,0); }
            #line 878 "yparser.c"
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 44:
            /* ruleItem -> <block>  */
            #line 130 "yparser.y"
            { YGBuilder_addBlockItem(yydata,(yyparser->sp[-1]).image,(yyparser->sp[-1]).line); }
            #line 886 "yparser.c"
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
    }
    yyparser->sLen -= yyruleLen[yyrule];
    int yyindex = YYSTATE() * yyntCount + yylhs[yyrule];
    YYPUSH_STATE(yygoto[yyindex] - 1);
    return 0;
}
int yyParser_init(yyParser *yyparser){
    yyparser->sLen = 1;
    yyparser->done = 0;
    yyparser->sSize = yyparser->pSize = 16;
    yyparser->state = (int *)YYMALLOC(sizeof(int) * yyparser->sSize);
    yyparser->state[0] = 0;
    yyparser->sp = yyparser->pstack = (YToken *)YYMALLOC(sizeof(YToken) * yyparser->pSize);
    return 0;
}
int yyParser_reInit(yyParser *yyparser){
    yyparser->sLen = 0;
    yyparser->done = 0;
    yyparser->state[0] = 0;
    yyparser->sp = yyparser->pstack;
    return 0;
}
int yyParser_free(yyParser *yyparser){
    YYFREE(yyparser->state);
    YYFREE(yyparser->pstack);
    return 0;
}
int yyParser_acceptToken(yyParser *yyparser,int yytokenid){
    int shifted = 0;
    while(!shifted){
        int yyaction = yyshift[YYSTATE() * yytokenCount + yytokenid];
        if(yyaction > 0){
            YYCHECK_PUSH_TOKEN();
            *yyparser->sp++ = yyparser->token;
            YYPUSH_STATE(yyaction - 1);
            shifted = 1;
        }
        else if(yyaction < 0){
            if(yyaction == -1){
                yyparser->done = 1;
                return YY_OK;
            }
            yyParser_reduce(yyparser,-1 - yyaction);
        }
        else {
            yyparser->error = 1;
            yyparser->errToken = yytokenid;
            return YY_ERR;
        }
    }
    return YY_OK;
}
int yyParser_printError(yyParser *yyparser,FILE *out){
    if(yyparser->error){
        int index = YYSTATE() * yytokenCount;
        fprintf(out,"unexpected token '%s' (%s),was expecting one of:\n",yytokenNames[yyparser->errToken],yytokenAlias[yyparser->errToken]);
        int i;
        for(i = 0;i < yytokenCount;i++){
            if(yyshift[index + i] != 0){
                fprintf(out,"    '%s' (%s) ...\n",yytokenNames[i],yytokenAlias[i]);
            }
        }
    }
    return YY_OK;
}
int yyParser_clearStack(yyParser *yyparser){
    while(yyparser->sp > yyparser->pstack){
        yyparser->sp--;
        YYDESTRUCTOR(yyparser->sp);
    }
    return 0;
}
