/*
    Generated by yapc -- An LR(1) parser generator made by CFY
*/



#include <stdio.h>
#include "grammar_builder.h"
#include "grammar.h"
#include "spool.h"

#include "yparser.h"
static const int yytokenCount = 18;
static const int yyntCount = 15;
#ifndef YYMALLOC
    #define YYMALLOC malloc
#endif
#ifndef YYREALLOC
    #define YYREALLOC realloc
#endif
#ifndef YYFREE
    #define YYFREE free
#endif
#ifndef YYDESTRUCTOR
    #define YYDESTRUCTOR(a)
#endif
#define YYPUSH_STATE(s) \
    if(yyparser->sLen >= yyparser->sSize){ \
        yyparser->sSize *= 2; \
        yyparser->state = (int *)YYREALLOC(yyparser->state,sizeof(int) * yyparser->sSize); \
    } \
    yyparser->state[yyparser->sLen++] = (s);

#define YYSTATE() (yyparser->state[yyparser->sLen - 1])
#define YYCHECK_PUSH_TOKEN() \
    if(yyparser->sp - yyparser->pstack >= yyparser->pSize){\
        size_t offset = yyparser->sp - yyparser->pstack;\
        yyparser->pSize *= 2;\
        yyparser->pstack = (YToken *)YYREALLOC(yyparser->pstack,sizeof(YToken) * yyparser->pSize);\
        yyparser->sp = yyparser->pstack + offset;\
    }
/*
    shift action table
    positive numbers indicate the states shift to,
    negative numbers indicate the rules reduce with.
    the state should be the number in the table minus one,since zero marks
    for error.
*/
static const int yyshift[] = {
    /* state 0 */
         0,   -12,   -12,   -12,     0,     0,   -12,   -12,   -12,   -12,     0,
         0,     0,     0,     0,     0,     0,    42,
    /* state 1 */
        -1,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,
    /* state 2 */
         0,    -4,    -4,    -4,     0,     0,    -4,    -4,    -4,    -4,     0,
         0,     0,     0,     0,     0,     0,     0,
    /* state 3 */
         0,    30,    33,    35,     0,     0,    37,    41,    39,     5,     0,
         0,     0,     0,     0,     0,     0,     0,
    /* state 4 */
         0,     0,     0,     0,    26,     0,     0,     0,     0,     0,     0,
         0,     0,    14,     0,     0,     0,     0,
    /* state 5 */
         0,     0,     0,     0,    26,     0,     0,     0,     0,     7,     0,
         0,     0,    14,     0,     0,     0,     0,
    /* state 6 */
        -2,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,
    /* state 7 */
         0,     0,     0,     0,   -13,     0,     0,     0,     0,   -13,     0,
         0,     0,   -13,     0,     0,     0,     0,
    /* state 8 */
         0,     0,     0,     0,   -14,     0,     0,     0,     0,   -14,     0,
         0,     0,   -14,     0,     0,     0,     0,
    /* state 9 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,    11,     0,     0,     0,     0,     0,
    /* state 10 */
         0,     0,     0,     0,   -15,     0,     0,     0,     0,   -15,     0,
         0,     0,   -15,     0,     0,     0,     0,
    /* state 11 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,    13,     0,     0,     0,     0,     0,
    /* state 12 */
         0,     0,     0,     0,   -16,     0,     0,     0,     0,   -16,     0,
         0,     0,   -16,     0,     0,     0,     0,
    /* state 13 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,   -20,
         0,     0,     0,     0,     0,     0,     0,
    /* state 14 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,    16,
         0,     0,     0,     0,     0,     0,     0,
    /* state 15 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       -26,   -26,   -26,   -26,     0,   -26,     0,
    /* state 16 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       -23,   -21,     0,     0,     0,     0,     0,
    /* state 17 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
        19,     0,     0,     0,     0,     0,     0,
    /* state 18 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       -26,   -26,   -26,   -26,     0,   -26,     0,
    /* state 19 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       -24,   -24,    23,    22,     0,    24,     0,
    /* state 20 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       -25,   -25,   -25,   -25,     0,   -25,     0,
    /* state 21 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       -27,   -27,   -27,   -27,     0,   -27,     0,
    /* state 22 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       -28,   -28,   -28,   -28,     0,   -28,     0,
    /* state 23 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       -29,   -29,   -29,   -29,     0,   -29,     0,
    /* state 24 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       -22,   -22,    23,    22,     0,    24,     0,
    /* state 25 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,   -19,     0,   -19,     0,     0,     0,
    /* state 26 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,   -17,     0,    28,     0,     0,     0,
    /* state 27 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,   -18,     0,   -18,     0,     0,     0,
    /* state 28 */
         0,    -3,    -3,    -3,     0,     0,    -3,    -3,    -3,    -3,     0,
         0,     0,     0,     0,     0,     0,     0,
    /* state 29 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,    31,     0,     0,     0,
    /* state 30 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,    32,     0,     0,
    /* state 31 */
         0,    -5,    -5,    -5,     0,     0,    -5,    -5,    -5,    -5,     0,
         0,     0,     0,     0,     0,     0,     0,
    /* state 32 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,    34,     0,     0,
    /* state 33 */
         0,    -6,    -6,    -6,     0,     0,    -6,    -6,    -6,    -6,     0,
         0,     0,     0,     0,     0,     0,     0,
    /* state 34 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,    36,     0,     0,
    /* state 35 */
         0,    -7,    -7,    -7,     0,     0,    -7,    -7,    -7,    -7,     0,
         0,     0,     0,     0,     0,     0,     0,
    /* state 36 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,    38,     0,     0,
    /* state 37 */
         0,    -8,    -8,    -8,     0,     0,    -8,    -8,    -8,    -8,     0,
         0,     0,     0,     0,     0,     0,     0,
    /* state 38 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,    40,     0,     0,
    /* state 39 */
         0,    -9,    -9,    -9,     0,     0,    -9,    -9,    -9,    -9,     0,
         0,     0,     0,     0,     0,     0,     0,
    /* state 40 */
         0,   -10,   -10,   -10,     0,     0,   -10,   -10,   -10,   -10,     0,
         0,     0,     0,     0,     0,     0,     0,
    /* state 41 */
         0,   -11,   -11,   -11,     0,     0,   -11,   -11,   -11,   -11,     0,
         0,     0,     0,     0,     0,     0,     0,
};
/*
    goto table
*/
static const int yygoto[] = {
    /* state 0 */
         0,     2,     0,     0,     3,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 1 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 2 */
         0,     0,     4,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 3 */
         0,     0,     0,    29,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 4 */
         0,     0,     0,     0,     0,     6,     9,    12,     0,    10,     0,
         0,     0,     0,     0,
    /* state 5 */
         0,     0,     0,     0,     0,     0,     8,    12,     0,    10,     0,
         0,     0,     0,     0,
    /* state 6 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 7 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 8 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 9 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 10 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 11 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 12 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 13 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,    15,
         0,     0,     0,     0,
    /* state 14 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 15 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
        17,     0,    25,     0,
    /* state 16 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,    18,     0,     0,
    /* state 17 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 18 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,    20,     0,
    /* state 19 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,    21,
    /* state 20 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 21 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 22 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 23 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 24 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,    21,
    /* state 25 */
         0,     0,     0,     0,     0,     0,     0,     0,    27,     0,     0,
         0,     0,     0,     0,
    /* state 26 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 27 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 28 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 29 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 30 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 31 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 32 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 33 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 34 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 35 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 36 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 37 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 38 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 39 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 40 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
    /* state 41 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,
};
/*
    the left hand side of each rule,used to determine goto action.
*/
static const int yylhs[] = {
         0,     1,     2,     2,     3,     3,     3,     3,     3,     3,     4,
         4,     5,     5,     6,     6,     7,     8,     8,    10,     9,    11,
        12,    11,    13,    13,    14,    14,    14,
};
/*
    the length of the symbols on the rhs of each rule
    used to pop states from the state stack when doing
    an reduction.
*/
static const int yyruleLen[] = {
         1,     5,     2,     0,     3,     2,     2,     2,     2,     1,     1,
         0,     2,     1,     2,     2,     2,     2,     0,     0,     4,     1,
         0,     4,     2,     0,     1,     1,     1,
};
const char *yytokenNames[] = {
    "EOF","%token","%type","%datatype","%test","%empty",
    "%token_prefix","%enable_cst","%ns","%%",":","|",
    ";","name","token","string","block","prologue",
    
};
const char *yytokenAlias[] = {
    "EOF","TOKEN_DIR","TYPE_DIR","DATATYPE_DIR","TEST_DIR","EMPTY_DIR",
    "TOKEN_PREFIX_DIR","ENABLE_CST_DIR","NS_DIR","SEPERATOR","ARROW","OR",
    "EOL","NAME","TOKEN","STRING","BLOCK","PROLOGUE",
    
};
const char *yynonTerminals[] = {
    "(accept)","file","options","option","prologue","body",
    "bodyItem","test","tokenList","rule","@1","ruleBody",
    "@2","ruleItems","ruleItem",
};
static int yyParser_reduce(yyParser *yyparser,int yyrule){
    YYCHECK_PUSH_TOKEN();
    YToken yyval;
    YGBuilder *yydata = (YGBuilder *)yyparser->userData;
    switch(yyrule){
        case 0:
            /* (accept) -> file  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 1:
            /* file -> prologue options <%%> body <%%>  */
            /* no action. */
            yyval = yyparser->sp[-5];
            yyparser->sp -= 5;
            *yyparser->sp++ = yyval;
            break;
        case 2:
            /* options -> options option  */
            /* no action. */
            yyval = yyparser->sp[-2];
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 3:
            /* options ->  */
            /* no action. */
            yyval = yyparser->sp[0];
            *yyparser->sp++ = yyval;
            break;
        case 4:
            /* option -> <%token> <token> <string>  */
            #line 70 "yparser.y"
            { YGBuilder_addToken(yydata,(yyparser->sp[-2]).image,(yyparser->sp[-1]).image); }
            #line 380 "yparser.c"
            yyparser->sp -= 3;
            *yyparser->sp++ = yyval;
            break;
        case 5:
            /* option -> <%type> <string>  */
            #line 71 "yparser.y"
            { yydata->stype = (yyparser->sp[-1]).image; }
            #line 388 "yparser.c"
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 6:
            /* option -> <%datatype> <string>  */
            #line 72 "yparser.y"
            { yydata->dataType = (yyparser->sp[-1]).image; }
            #line 396 "yparser.c"
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 7:
            /* option -> <%token_prefix> <string>  */
            #line 73 "yparser.y"
            { yydata->tokenPrefix = (yyparser->sp[-1]).image; }
            #line 404 "yparser.c"
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 8:
            /* option -> <%ns> <string>  */
            #line 74 "yparser.y"
            { yydata->nameSpace = (yyparser->sp[-2]).image; }
            #line 412 "yparser.c"
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 9:
            /* option -> <%enable_cst>  */
            #line 75 "yparser.y"
            { yydata->genCst = 1; }
            #line 420 "yparser.c"
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 10:
            /* prologue -> <prologue>  */
            #line 77 "yparser.y"
            { yydata->prologue = (yyparser->sp[-1]).image; }
            #line 428 "yparser.c"
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 11:
            /* prologue ->  */
            /* no action. */
            yyval = yyparser->sp[0];
            *yyparser->sp++ = yyval;
            break;
        case 12:
            /* body -> body bodyItem  */
            /* no action. */
            yyval = yyparser->sp[-2];
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 13:
            /* body -> bodyItem  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 14:
            /* bodyItem -> rule <;>  */
            /* no action. */
            yyval = yyparser->sp[-2];
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 15:
            /* bodyItem -> test <;>  */
            /* no action. */
            yyval = yyparser->sp[-2];
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 16:
            /* test -> <%test> tokenList  */
            /* no action. */
            yyval = yyparser->sp[-2];
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 17:
            /* tokenList -> tokenList <token>  */
            #line 85 "yparser.y"
            { YGBuilder_addTestToken(yydata,(yyparser->sp[-1]).image); }
            #line 477 "yparser.c"
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 18:
            /* tokenList ->  */
            /* no action. */
            yyval = yyparser->sp[0];
            *yyparser->sp++ = yyval;
            break;
        case 19:
            /* @1 ->  */
            #line 88 "yparser.y"
            { yydata->lhs = (yyparser->sp[-1]).image;YGBuilder_prepareRule(yydata,yydata->lhs); }
            #line 491 "yparser.c"
            break;
        case 20:
            /* rule -> <name> @1 <:> ruleBody  */
            /* no action. */
            yyval = yyparser->sp[-3];
            yyparser->sp -= 3;
            *yyparser->sp++ = yyval;
            break;
        case 21:
            /* ruleBody -> ruleItems  */
            #line 91 "yparser.y"
            { YGBuilder_commitRule(yydata); }
            #line 504 "yparser.c"
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 22:
            /* @2 ->  */
            #line 92 "yparser.y"
            { YGBuilder_prepareRule(yydata,yydata->lhs); }
            #line 512 "yparser.c"
            break;
        case 23:
            /* ruleBody -> ruleBody @2 <|> ruleItems  */
            #line 92 "yparser.y"
            { YGBuilder_commitRule(yydata); }
            #line 518 "yparser.c"
            yyparser->sp -= 3;
            *yyparser->sp++ = yyval;
            break;
        case 24:
            /* ruleItems -> ruleItems ruleItem  */
            /* no action. */
            yyval = yyparser->sp[-2];
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 25:
            /* ruleItems ->  */
            /* no action. */
            yyval = yyparser->sp[0];
            *yyparser->sp++ = yyval;
            break;
        case 26:
            /* ruleItem -> <token>  */
            #line 97 "yparser.y"
            { YGBuilder_addRuleItem(yydata,(yyparser->sp[-1]).image,1); }
            #line 539 "yparser.c"
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 27:
            /* ruleItem -> <name>  */
            #line 98 "yparser.y"
            { YGBuilder_addRuleItem(yydata,(yyparser->sp[-1]).image,0); }
            #line 547 "yparser.c"
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 28:
            /* ruleItem -> <block>  */
            #line 99 "yparser.y"
            { YGBuilder_addBlockItem(yydata,(yyparser->sp[-1]).image,(yyparser->sp[-1]).line); }
            #line 555 "yparser.c"
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
    }
    yyparser->sLen -= yyruleLen[yyrule];
    int yyindex = YYSTATE() * yyntCount + yylhs[yyrule];
    YYPUSH_STATE(yygoto[yyindex] - 1);
    return 0;
}
int yyParser_init(yyParser *yyparser){
    yyparser->sLen = 1;
    yyparser->done = 0;
    yyparser->sSize = yyparser->pSize = 16;
    yyparser->state = (int *)YYMALLOC(sizeof(int) * yyparser->sSize);
    yyparser->state[0] = 0;
    yyparser->sp = yyparser->pstack = (YToken *)YYMALLOC(sizeof(YToken) * yyparser->pSize);
    return 0;
}
int yyParser_reInit(yyParser *yyparser){
    yyparser->sLen = 0;
    yyparser->done = 0;
    yyparser->state[0] = 0;
    yyparser->sp = yyparser->pstack;
    return 0;
}
int yyParser_free(yyParser *yyparser){
    YYFREE(yyparser->state);
    YYFREE(yyparser->pstack);
    return 0;
}
int yyParser_acceptToken(yyParser *yyparser,int yytokenid){
    int shifted = 0;
    while(!shifted){
        int yyaction = yyshift[YYSTATE() * yytokenCount + yytokenid];
        if(yyaction > 0){
            YYCHECK_PUSH_TOKEN();
            *yyparser->sp++ = yyparser->token;
            YYPUSH_STATE(yyaction - 1);
            shifted = 1;
        }
        else if(yyaction < 0){
            if(yyaction == -1){
                yyparser->done = 1;
                return YY_OK;
            }
            yyParser_reduce(yyparser,-1 - yyaction);
        }
        else {
            yyparser->error = 1;
            yyparser->errToken = yytokenid;
            return YY_ERR;
        }
    }
    return YY_OK;
}
int yyParser_printError(yyParser *yyparser,FILE *out){
    if(yyparser->error){
        int index = YYSTATE() * yytokenCount;
        fprintf(out,"unexpected token '%s' (%s),was expecting one of:\n",yytokenNames[yyparser->errToken],yytokenAlias[yyparser->errToken]);
        int i;
        for(i = 0;i < yytokenCount;i++){
            if(yyshift[index + i] != 0){
                fprintf(out,"    '%s' (%s) ...\n",yytokenNames[i],yytokenAlias[i]);
            }
        }
    }
    return YY_OK;
}
int yyParser_clearStack(yyParser *yyparser){
    while(yyparser->sp > yyparser->pstack){
        yyparser->sp--;
        YYDESTRUCTOR(yyparser->sp);
    }
    return 0;
}
