/*
    Generated by yapc -- An LR(1) parser generator made by CFY
*/

#ifndef __YY_H__
#define __YY_H__

#include <stdlib.h>
#include <stdio.h>
#define T_EOF 0
#define T_BEGIN 1
#define T_END 2
#define T_INTEGER 3
#define T_IF 4
#define T_THEN 5
#define T_ELSE 6
#define T_FUNCTION 7
#define T_READ 8
#define T_WRITE 9
#define T_ID 10
#define T_NUM 11
#define T_EQ 12
#define T_NE 13
#define T_LTOE 14
#define T_LT 15
#define T_GTOE 16
#define T_GT 17
#define T_MINUS 18
#define T_MULTIPLY 19
#define T_ASSIGN 20
#define T_BRA 21
#define T_KET 22
#define T_SEMI_COLLON 23
#define T_COMMA 24




typedef struct _yyParser{
    //state stack
    int *state;
    int sLen,sSize;
    //sematic stack
    int *pstack,*sp;
    int pSize;
    //current token,this token would be accepted
    //when yyParser_acceptTokenis called.
    int token;
    //this would be set to 1 when input is accepted.
    int done;
    //this would be set to 1 when a syntax error is detected.
    int error,errToken;
    //the generic pointer that user can set
    void *userData;
}yyParser;


int yyParser_init(yyParser *yyparser);
int yyParser_reInit(yyParser *yyparser);
int yyParser_free(yyParser *yyparser);
int yyParser_acceptToken(yyParser *yyparser,int yytokenid);
int yyParser_printError(yyParser *yyparser,FILE *out);
int yyParser_clearStack(yyParser *yyparser);


#endif