/*
    Generated by yapc -- An LR(1) parser generator made by CFY
*/

#include "parser.h"
static const int yytokenCount = 24;
static const int yyntCount = 21;
#ifndef YYMALLOC
    #define YYMALLOC malloc
#endif
#ifndef YYREALLOC
    #define YYREALLOC realloc
#endif
#ifndef YYFREE
    #define YYFREE free
#endif
#ifndef YYDESTRUCTOR
    #define YYDESTRUCTOR(a)
#endif
#define YYPUSH_STATE(s) \
    if(yyparser->sLen >= yyparser->sSize){ \
        yyparser->sSize *= 2; \
        yyparser->state = (int *)YYREALLOC(yyparser->state,sizeof(int) * yyparser->sSize); \
    } \
    yyparser->state[yyparser->sLen++] = (s);

#define YYSTATE() (yyparser->state[yyparser->sLen - 1])
#define YYCHECK_PUSH_TOKEN() \
    if(yyparser->sp - yyparser->pstack >= yyparser->pSize){\
        size_t offset = yyparser->sp - yyparser->pstack;\
        yyparser->pSize *= 2;\
        yyparser->pstack = (int *)YYREALLOC(yyparser->pstack,sizeof(int) * yyparser->pSize);\
        yyparser->sp = yyparser->pstack + offset;\
    }
/*
    shift action table
    positive numbers indicate the states shift to,
    negative numbers indicate the rules reduce with.
    the state should be the number in the table minus one,since zero marks
    for error.
*/
static const int yyshift[] = {
    /* state 0 */
         0,     4,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 1 */
        -1,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 2 */
        -2,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 3 */
         0,     0,     0,    58,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 4 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     6,
    /* state 5 */
         0,     0,     0,    58,    17,     0,     0,     0,    51,    47,    73,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 6 */
         0,     0,     8,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     9,
    /* state 7 */
        -3,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 8 */
         0,     0,     0,     0,    17,     0,     0,     0,    51,    47,    73,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 9 */
         0,     0,   -14,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,   -14,
    /* state 10 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,    -4,
    /* state 11 */
         0,     0,   -13,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,   -13,
    /* state 12 */
         0,     0,   -18,     0,     0,     0,   -18,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,   -18,
    /* state 13 */
         0,     0,   -17,     0,     0,     0,   -17,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,   -17,
    /* state 14 */
         0,     0,   -16,     0,     0,     0,   -16,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,   -16,
    /* state 15 */
         0,     0,   -15,     0,     0,     0,   -15,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,   -15,
    /* state 16 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,    42,
        46,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 17 */
         0,     0,     0,     0,     0,    19,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 18 */
         0,     0,     0,     0,    17,     0,     0,     0,    51,    47,    73,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 19 */
         0,     0,     0,     0,     0,     0,    21,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 20 */
         0,     0,     0,     0,    17,     0,     0,     0,    51,    47,    73,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 21 */
         0,     0,   -28,     0,     0,     0,   -28,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,   -28,
    /* state 22 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,    27,    26,    29,    31,    28,    30,    37,    35,     0,     0,
         0,     0,
    /* state 23 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,    42,
        46,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 24 */
         0,     0,     0,     0,     0,   -29,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,    37,    35,     0,     0,
         0,     0,
    /* state 25 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,   -35,
       -35,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 26 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,   -34,
       -34,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 27 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,   -33,
       -33,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 28 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,   -32,
       -32,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 29 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,   -31,
       -31,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 30 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,   -30,
       -30,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 31 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,    33,     0,
         0,     0,
    /* state 32 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,    42,
        46,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 33 */
         0,     0,   -21,     0,     0,     0,   -21,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,    37,    35,     0,     0,
         0,   -21,
    /* state 34 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,    42,
        46,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 35 */
         0,     0,   -23,     0,     0,   -23,   -23,     0,     0,     0,     0,
         0,   -23,   -23,   -23,   -23,   -23,   -23,   -23,   -23,     0,     0,
       -23,   -23,
    /* state 36 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,    42,
        46,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 37 */
         0,     0,   -22,     0,     0,   -22,   -22,     0,     0,     0,     0,
         0,   -22,   -22,   -22,   -22,   -22,   -22,   -22,    35,     0,     0,
       -22,   -22,
    /* state 38 */
         0,     0,   -26,     0,     0,   -26,   -26,     0,     0,     0,     0,
         0,   -26,   -26,   -26,   -26,   -26,   -26,   -26,   -26,     0,     0,
       -26,   -26,
    /* state 39 */
         0,     0,   -25,     0,     0,   -25,   -25,     0,     0,     0,     0,
         0,   -25,   -25,   -25,   -25,   -25,   -25,   -25,   -25,     0,     0,
       -25,   -25,
    /* state 40 */
         0,     0,   -24,     0,     0,   -24,   -24,     0,     0,     0,     0,
         0,   -24,   -24,   -24,   -24,   -24,   -24,   -24,   -24,     0,     0,
       -24,   -24,
    /* state 41 */
         0,     0,    -9,     0,     0,    -9,    -9,     0,     0,     0,     0,
         0,    -9,    -9,    -9,    -9,    -9,    -9,    -9,    -9,     0,    43,
        -9,    -9,
    /* state 42 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,    42,
        46,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 43 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,    37,    35,     0,     0,
        45,     0,
    /* state 44 */
         0,     0,   -36,     0,     0,   -36,   -36,     0,     0,     0,     0,
         0,   -36,   -36,   -36,   -36,   -36,   -36,   -36,   -36,     0,     0,
       -36,   -36,
    /* state 45 */
         0,     0,   -27,     0,     0,   -27,   -27,     0,     0,     0,     0,
         0,   -27,   -27,   -27,   -27,   -27,   -27,   -27,   -27,     0,     0,
       -27,   -27,
    /* state 46 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,    48,
         0,     0,
    /* state 47 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,    73,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 48 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
        50,     0,
    /* state 49 */
         0,     0,   -20,     0,     0,     0,   -20,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,   -20,
    /* state 50 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,    52,
         0,     0,
    /* state 51 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,    73,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 52 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
        54,     0,
    /* state 53 */
         0,     0,   -19,     0,     0,     0,   -19,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,   -19,
    /* state 54 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,    -5,
    /* state 55 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,    -7,
    /* state 56 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,    -6,
    /* state 57 */
         0,     0,     0,     0,     0,     0,     0,    59,     0,     0,    73,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 58 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,    60,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 59 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,    61,
         0,     0,
    /* state 60 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,    73,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 61 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
        63,     0,
    /* state 62 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,    64,
    /* state 63 */
         0,    66,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 64 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,   -10,
    /* state 65 */
         0,     0,     0,    58,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 66 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,    68,
    /* state 67 */
         0,     0,     0,    58,    17,     0,     0,     0,    51,    47,    73,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,
    /* state 68 */
         0,     0,    70,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     9,
    /* state 69 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,   -12,
    /* state 70 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       -11,     0,
    /* state 71 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,    -8,
    /* state 72 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,    -9,     0,
        -9,    -9,
};
/*
    goto table
*/
static const int yygoto[] = {
    /* state 0 */
         0,     2,     3,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 1 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 2 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 3 */
         0,     0,     0,     5,    55,    57,     0,    56,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 4 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 5 */
         0,     0,     0,     0,    11,    57,    32,    56,     0,     0,     7,
        12,    16,    15,    14,     0,     0,    13,     0,     0,     0,
    /* state 6 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 7 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 8 */
         0,     0,     0,     0,     0,     0,    32,     0,     0,     0,     0,
        10,    16,    15,    14,     0,     0,    13,     0,     0,     0,
    /* state 9 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 10 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 11 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 12 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 13 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 14 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 15 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 16 */
         0,     0,     0,     0,     0,     0,    40,     0,     0,     0,     0,
         0,     0,     0,     0,    23,    41,     0,    18,     0,    39,
    /* state 17 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 18 */
         0,     0,     0,     0,     0,     0,    32,     0,     0,     0,     0,
        20,    16,    15,    14,     0,     0,    13,     0,     0,     0,
    /* state 19 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 20 */
         0,     0,     0,     0,     0,     0,    32,     0,     0,     0,     0,
        22,    16,    15,    14,     0,     0,    13,     0,     0,     0,
    /* state 21 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 22 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,    24,     0,
    /* state 23 */
         0,     0,     0,     0,     0,     0,    40,     0,     0,     0,     0,
         0,     0,     0,     0,    25,    41,     0,     0,     0,    39,
    /* state 24 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 25 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 26 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 27 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 28 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 29 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 30 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 31 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 32 */
         0,     0,     0,     0,     0,     0,    40,     0,     0,     0,     0,
         0,     0,     0,     0,    34,    41,     0,     0,     0,    39,
    /* state 33 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 34 */
         0,     0,     0,     0,     0,     0,    40,     0,     0,     0,     0,
         0,     0,     0,     0,    36,    41,     0,     0,     0,    39,
    /* state 35 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 36 */
         0,     0,     0,     0,     0,     0,    40,     0,     0,     0,     0,
         0,     0,     0,     0,    38,    41,     0,     0,     0,    39,
    /* state 37 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 38 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 39 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 40 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 41 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 42 */
         0,     0,     0,     0,     0,     0,    40,     0,     0,     0,     0,
         0,     0,     0,     0,    44,    41,     0,     0,     0,    39,
    /* state 43 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 44 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 45 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 46 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 47 */
         0,     0,     0,     0,     0,     0,    49,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 48 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 49 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 50 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 51 */
         0,     0,     0,     0,     0,     0,    53,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 52 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 53 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 54 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 55 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 56 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 57 */
         0,     0,     0,     0,     0,     0,    72,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 58 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 59 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 60 */
         0,     0,     0,     0,     0,     0,    71,     0,    62,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 61 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 62 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 63 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,    65,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 64 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 65 */
         0,     0,     0,    67,    55,    57,     0,    56,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 66 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 67 */
         0,     0,     0,     0,    11,    57,    32,    56,     0,     0,    69,
        12,    16,    15,    14,     0,     0,    13,     0,     0,     0,
    /* state 68 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 69 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 70 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 71 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    /* state 72 */
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
         0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
};
/*
    the left hand side of each rule,used to determine goto action.
*/
static const int yylhs[] = {
         0,     1,     2,     3,     3,     4,     4,     5,     6,     7,     8,
         9,    10,    10,    11,    11,    11,    11,    12,    13,    14,    15,
        15,    15,    15,    15,    16,    17,    18,    19,    19,    19,    19,
        19,    19,    20,
};
/*
    the length of the symbols on the rhs of each rule
    used to pop states from the state stack when doing
    an reduction.
*/
static const int yyruleLen[] = {
         1,     1,     5,     3,     1,     1,     1,     2,     1,     8,     1,
         5,     1,     3,     1,     1,     1,     1,     4,     4,     3,     3,
         3,     1,     1,     1,     1,     6,     3,     1,     1,     1,     1,
         1,     1,     4,
};
const char *yytokenNames[] = {
    "EOF","begin","end","integer","if","then",
    "else","function","read","write","ID","NUM",
    "=","ne","ltoe","lt","gtoe","gt",
    "-","*",":=","(",")",";",
    
};
const char *yytokenAlias[] = {
    "EOF","BEGIN","END","INTEGER","IF","THEN",
    "ELSE","FUNCTION","READ","WRITE","ID","NUM",
    "EQ","NE","LTOE","LT","GTOE","GT",
    "MINUS","MULTIPLY","ASSIGN","BRA","KET","SEMI_COLLON",
    
};
const char *yynonTerminals[] = {
    "(accept)","program","subProgram","declList","decl","varDecl",
    "varID","funcDecl","argDefList","funcBody","stmtList","stmt",
    "readStmt","writeStmt","assignStmt","expr","constant","ifStmt",
    "cond","condOptr","funcCall",
};
static int yyParser_pushCst(yyParser *parser,int isT,int id,int length){
    if(parser->cstLen >= parser->cstSize){
        parser->cstSize *= 2;
        parser->cst = (yyCst *)YYREALLOC(parser->cst,sizeof(yyCst) * parser->cstSize);
    }
    if(parser->cLen >= parser->cSize){
        parser->cSize *= 2;
        parser->cStack = (int *)YYREALLOC(parser->cStack,sizeof(int) * parser->cSize);
    }
    yyCst *cst = parser->cst + parser->cstLen++;
    cst->index = parser->cstLen - 1;
    cst->id = id;
    cst->isTermi = isT;
    cst->level = 0;
    cst->length = length;
    cst->child = cst->cousin = -1;
    if(!isT){
        int i;
        for(i = parser->cLen - length;i < parser->cLen - 1;i++){
            parser->cst[parser->cStack[i]].cousin = parser->cst[parser->cStack[i + 1]].index;
        }
        cst->child = parser->cst[parser->cStack[parser->cLen - length]].index;
        parser->cLen -= length;
    }
    parser->cStack[parser->cLen++] = cst->index;
    return 0;
}
static int yyParser_reduce(yyParser *yyparser,int yyrule){
    YYCHECK_PUSH_TOKEN();
    int yyval;
    void *yydata = (void *)yyparser->userData;
    switch(yyrule){
        case 0:
            /* (accept) -> program  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 1:
            /* program -> subProgram  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 2:
            /* subProgram -> <begin> declList <;> stmtList <end>  */
            /* no action. */
            yyval = yyparser->sp[-5];
            yyparser->sp -= 5;
            *yyparser->sp++ = yyval;
            break;
        case 3:
            /* declList -> declList <;> decl  */
            /* no action. */
            yyval = yyparser->sp[-3];
            yyparser->sp -= 3;
            *yyparser->sp++ = yyval;
            break;
        case 4:
            /* declList -> decl  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 5:
            /* decl -> varDecl  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 6:
            /* decl -> funcDecl  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 7:
            /* varDecl -> <integer> varID  */
            /* no action. */
            yyval = yyparser->sp[-2];
            yyparser->sp -= 2;
            *yyparser->sp++ = yyval;
            break;
        case 8:
            /* varID -> <ID>  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 9:
            /* funcDecl -> <integer> <function> <ID> <(> argDefList <)> <;> funcBody  */
            /* no action. */
            yyval = yyparser->sp[-8];
            yyparser->sp -= 8;
            *yyparser->sp++ = yyval;
            break;
        case 10:
            /* argDefList -> varID  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 11:
            /* funcBody -> <begin> declList <;> stmtList <end>  */
            /* no action. */
            yyval = yyparser->sp[-5];
            yyparser->sp -= 5;
            *yyparser->sp++ = yyval;
            break;
        case 12:
            /* stmtList -> stmt  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 13:
            /* stmtList -> stmtList <;> stmt  */
            /* no action. */
            yyval = yyparser->sp[-3];
            yyparser->sp -= 3;
            *yyparser->sp++ = yyval;
            break;
        case 14:
            /* stmt -> readStmt  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 15:
            /* stmt -> writeStmt  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 16:
            /* stmt -> assignStmt  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 17:
            /* stmt -> ifStmt  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 18:
            /* readStmt -> <read> <(> varID <)>  */
            /* no action. */
            yyval = yyparser->sp[-4];
            yyparser->sp -= 4;
            *yyparser->sp++ = yyval;
            break;
        case 19:
            /* writeStmt -> <write> <(> varID <)>  */
            /* no action. */
            yyval = yyparser->sp[-4];
            yyparser->sp -= 4;
            *yyparser->sp++ = yyval;
            break;
        case 20:
            /* assignStmt -> varID <:=> expr  */
            /* no action. */
            yyval = yyparser->sp[-3];
            yyparser->sp -= 3;
            *yyparser->sp++ = yyval;
            break;
        case 21:
            /* expr -> expr <-> expr  */
            /* no action. */
            yyval = yyparser->sp[-3];
            yyparser->sp -= 3;
            *yyparser->sp++ = yyval;
            break;
        case 22:
            /* expr -> expr <*> expr  */
            /* no action. */
            yyval = yyparser->sp[-3];
            yyparser->sp -= 3;
            *yyparser->sp++ = yyval;
            break;
        case 23:
            /* expr -> constant  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 24:
            /* expr -> varID  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 25:
            /* expr -> funcCall  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 26:
            /* constant -> <NUM>  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 27:
            /* ifStmt -> <if> cond <then> stmt <else> stmt  */
            /* no action. */
            yyval = yyparser->sp[-6];
            yyparser->sp -= 6;
            *yyparser->sp++ = yyval;
            break;
        case 28:
            /* cond -> expr condOptr expr  */
            /* no action. */
            yyval = yyparser->sp[-3];
            yyparser->sp -= 3;
            *yyparser->sp++ = yyval;
            break;
        case 29:
            /* condOptr -> <lt>  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 30:
            /* condOptr -> <gt>  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 31:
            /* condOptr -> <ltoe>  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 32:
            /* condOptr -> <gtoe>  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 33:
            /* condOptr -> <=>  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 34:
            /* condOptr -> <ne>  */
            /* no action. */
            yyval = yyparser->sp[-1];
            yyparser->sp -= 1;
            *yyparser->sp++ = yyval;
            break;
        case 35:
            /* funcCall -> <ID> <(> expr <)>  */
            /* no action. */
            yyval = yyparser->sp[-4];
            yyparser->sp -= 4;
            *yyparser->sp++ = yyval;
            break;
    }
    yyparser->sLen -= yyruleLen[yyrule];
    int yyindex = YYSTATE() * yyntCount + yylhs[yyrule];
    YYPUSH_STATE(yygoto[yyindex] - 1);
    yyParser_pushCst(yyparser,0,yylhs[yyrule],yyruleLen[yyrule]);
    return 0;
}
int yyParser_init(yyParser *yyparser){
    yyparser->sLen = 1;
    yyparser->done = 0;
    yyparser->sSize = yyparser->pSize = 16;
    yyparser->state = (int *)YYMALLOC(sizeof(int) * yyparser->sSize);
    yyparser->state[0] = 0;
    yyparser->sp = yyparser->pstack = (int *)YYMALLOC(sizeof(int) * yyparser->pSize);
    yyparser->cstSize = 64;
    yyparser->cstLen = 0;
    yyparser->cst = (yyCst *)YYMALLOC(sizeof(yyCst) * yyparser->cstSize);
    yyparser->cLen = 0;
    yyparser->cSize = 16;
    yyparser->cStack = (int *)YYMALLOC(sizeof(int) * yyparser->cSize);
    return 0;
}
static int yyParser_clearStack(yyParser *yyparser){
    while(yyparser->sp > yyparser->pstack){
        yyparser->sp--;
        YYDESTRUCTOR(yyparser->sp);
    }
    return 0;
}
int yyParser_reInit(yyParser *yyparser){
    yyParser_clearStack(yyparser);
    yyparser->sLen = 0;
    yyparser->done = 0;
    yyparser->state[0] = 0;
    yyparser->sp = yyparser->pstack;
    yyparser->cstLen = 0;
    yyparser->cLen = 0;
    return 0;
}
int yyParser_free(yyParser *yyparser){
    yyParser_clearStack(yyparser);
    YYFREE(yyparser->state);
    YYFREE(yyparser->pstack);
YYFREE(yyparser->cst);
YYFREE(yyparser->cStack);
    return 0;
}
int yyParser_acceptToken(yyParser *yyparser,int yytokenid){
    int yyaction = yyshift[YYSTATE() * yytokenCount + yytokenid];
    if(yyaction > 0){
        YYCHECK_PUSH_TOKEN();
        *yyparser->sp++ = yyparser->token;
        YYPUSH_STATE(yyaction - 1);
        yyParser_pushCst(yyparser,1,yytokenid,0);
        return YY_SHIFT;
    }
    else if(yyaction < 0){
        if(yyaction == -1){
            yyparser->done = 1;
            return YY_ACCEPT;
        }
        yyParser_reduce(yyparser,-1 - yyaction);
        return YY_REDUCE;
    }
    else {
        yyparser->error = 1;
        yyparser->errToken = yytokenid;
        return YY_ERR;
    }
}
int yyParser_printError(yyParser *yyparser,FILE *out){
    if(yyparser->error){
        int index = YYSTATE() * yytokenCount;
        fprintf(out,"unexpected token '%s' (%s),was expecting one of:\n",yytokenNames[yyparser->errToken],yytokenAlias[yyparser->errToken]);
        int i;
        for(i = 0;i < yytokenCount;i++){
            if(yyshift[index + i] != 0){
                fprintf(out,"    '%s' (%s) ...\n",yytokenNames[i],yytokenAlias[i]);
            }
        }
    }
    return YY_OK;
}
/*
    following functions is for printing syntax trees in an elegant way.
*/
#define YYCCHR_DOWN "│   "
#define YYCCHR_CONNOR "└───"
#define YYCCHR_DIVERSE "├───"
#define YYCCHR_BLANK "    "
static void repeatPrint(FILE *out,const char *s,int count){
    while(count --> 0) fprintf(out,"%s",s);
}
static yyCst *yyCst_getChild(yyCst *array,yyCst *cst,int index){
    cst = array + cst->child;
    while(index --> 0){
        cst = array + cst->cousin;
    }
    return cst;
}
static int yyCst_printNode(yyCst *cst,yyCst **stack,int sp,FILE *out){
    int i,level = 0;
    for(i = 0;i < sp - 1;i++){
        repeatPrint(out,YYCCHR_BLANK,stack[i]->level - level - 1);
        fprintf(out,YYCCHR_DOWN);
        level = stack[i]->level;
    }
    if(sp > 0){
        repeatPrint(out,YYCCHR_BLANK,stack[i]->level - level - 1);
        if(stack[i]->printP < stack[i]->length - 1){
            fprintf(out,YYCCHR_DIVERSE);
        }
        else {
            fprintf(out,YYCCHR_CONNOR);
        }
    }
    if(cst->isTermi){
        fprintf(out,"<%s>\n",yytokenNames[cst->id]);
    }
    else{
        fprintf(out,"%s\n",yynonTerminals[cst->id]);
    }
    return YY_OK;
}
int yyParser_printCst(yyParser *parser,FILE *out){
    yyCst **cstack = (yyCst **)YYMALLOC(sizeof(yyCst *) * parser->cstLen);
    int sp = 0;
    yyCst *root = &parser->cst[parser->cStack[0]];
    root->printP = 0;
    root->level = 1;
    yyCst_printNode(root,cstack,sp,out);
    cstack[sp++] = root;
    while(sp > 0){
        yyCst *node = cstack[sp - 1];
        yyCst *childn = yyCst_getChild(parser->cst,node,node->printP);
        childn->level = node->level + 1;
        yyCst_printNode(childn,cstack,sp,out);
        if(++node->printP >= node->length){
            sp--;
        }
        if(childn->length > 0){
            cstack[sp++] = childn;
            childn->printP = 0;
        }
    }
    YYFREE(cstack);
    return YY_OK;
}
